[ADD] allow_filter on Odoo fields
openspp-project/openspp-registry pull request #136
Opened 2023-01-06 11:32 UTC by nhatnm0612

## What is PR does?

- Add a new field on `ir.model.fieds` model: `allow_filter` - Boolean, default=True.
- Add new abstract model `custom.filter.mixin` to override `fields_get` method: editing searchable attribute on Odoo fields, so if allow_filter is declared as False, field won't be shown on Custom Filter.

2023-01-06 11:38 UTC, nhatnm0612 commented
@jeremi I really need the fields list that is not allow to search in custom filter

2023-01-09 01:56 UTC, jeremi commented
@nhatnm0612 any field that we are not using in the UI can be excluded for now.

2023-01-10 02:24 UTC, jeremi requested changes

2023-01-10 02:24 UTC, jeremi commented on spp_custom_filter/models/custom_filter_mixin.py
> +        """
Use restructured format

2023-01-11 01:39 UTC, nhatnm0612 commented on spp_custom_filter/models/custom_filter_mixin.py
> +        """
I done it, please re-review

2023-01-11 03:47 UTC, jeremi approved these changes

2023-01-11 03:47 UTC, merged