able to hide edit button conditionally
openspp-project/openspp-registry pull request #148
Opened 2023-01-12 11:47 UTC by reichie020212

2023-01-12 13:12 UTC, jeremi commented
@gonzalesedwin1123 @nhatnm0612 Do you know if there is a cleaner way to do this ?

2023-01-12 14:21 UTC, nhatnm0612 commented
> @gonzalesedwin1123 @nhatnm0612 Do you know if there is a cleaner way to do this ?

why we don't use record rule feature?

2023-01-12 23:15 UTC, gonzalesedwin1123 commented
> @gonzalesedwin1123 @nhatnm0612 Do you know if there is a cleaner way to do this ?

I think this is a cleaner way to do this:
@reichie020212 you can try this javascript, which is similar to what we use in the 'Create Program' Wizard:
`odoo.define('<<module.custom_form_view>>', function (require) {
"use strict";

var core = require('web.core');
var FormController = require('web.FormController');

var _t = core._t;
var QWeb = core.qweb;

FormController.include({
    updateButtons: function () {
        if (this.modelName === "<<model.name>>") {
            if (this.renderer.state.data.state !== "draft") {
                this.$buttons.find('.o_form_button_edit')
                        .toggleClass('o_hidden', true);
            } else {
                this.$buttons.find('.o_form_button_edit')
                        .toggleClass('o_hidden', false);
            }
        } else {
            this.$buttons.find('.o_form_button_edit')
                    .toggleClass('o_hidden', false);
        }
        var edit_mode = (this.mode === 'edit');
        this.$buttons.find('.o_form_buttons_edit')
            .toggleClass('o_hidden', !edit_mode);
        this.$buttons.find('.o_form_buttons_view')
            .toggleClass('o_hidden', edit_mode);
    },
});

});`

2023-01-12 23:18 UTC, gonzalesedwin1123 requested changes

2023-01-12 23:18 UTC, gonzalesedwin1123 commented on spp_change_request/models/change_request.py
> +    )
Try the javascript solution in my comment.

2023-01-13 01:54 UTC, gonzalesedwin1123 commented on spp_change_request/models/change_request.py
> +    )
As @nhatnm0612 suggested, you can try adding a record rule that is applied only to 'edit' for addressing the requirement of allowing the editing of fields only for users assigned to the CR.

2023-01-13 02:19 UTC, nhatnm0612 commented on spp_change_request/models/change_request.py
> +                # Hide edit button when state is 'draft' and current user is not in either create_uid or assign_to_id
@reichie020212 this logic tell me that: if the record state is "draft" && the creator and assignee must be the current user to edit this record?

2023-01-13 10:08 UTC, nhatnm0612 commented on spp_change_request/static/src/js/hide_button.js
> +            }
```suggestion
            var renderStateData = this.renderer.state.data;
            if (!(
                this.$buttons &&
                renderStateData.assign_to_id &&
                renderStateData.assign_to_id.data &&
                renderStateData.create_uid &&
                renderStateData.create_uid.data
            )) {
                return;
            }
            if (
                this.modelName === 'app.change.request' &&
                renderStateData.state === 'draft' &&
                renderStateData.assign_to_id.data.id !== user &&
                renderStateData.create_uid.data.id !== user
            ) {
                this.$buttons.find('.o_form_button_edit').toggleClass('o_hidden', true);
            } else {
                this.$buttons.find('.o_form_button_edit').toggleClass('o_hidden', false);
            }
            var editMode = this.mode === 'edit';
            
             this.$buttons.find(".o_form_buttons_edit").toggleClass("o_hidden", !edit_mode);
             this.$buttons.find(".o_form_buttons_view").toggleClass("o_hidden", edit_mode);
```
really think that guard logic will improve the code readability.

2023-01-13 11:24 UTC, gonzalesedwin1123 approved these changes

2023-01-13 11:40 UTC, merged