Create Wizard for Creating Member
openspp-project/openspp-registry pull request #218
Opened 2023-04-13 15:23 UTC by emjay0921

2023-04-14 04:04 UTC, nhatnm0612 approved these changes, later dismissed

2023-04-19 03:33 UTC, jeremi requested changes
Can you add the additional details to the wizard ?

2023-05-04 00:26 UTC, gonzalesedwin1123 approved these changes

2023-05-04 03:12 UTC, jeremi requested changes
please improve the test coverage before we merge it.

2023-06-05 03:11 UTC, nhatnm0612 commented on spp_registry_wizard/wizard/create_member_wizard.py
> +                ):
```suggestion
              if (
                  self.env.ref(
                      "g2p_registry_membership.group_membership_kind_head"
                  ) in rec.role
                  and rec.head_member
              ):
```

2023-12-07 05:00 UTC, nhatnm0612 approved these changes

2023-12-07 05:00 UTC, nhatnm0612 commented on spp_registry_wizard/wizard/create_member_wizard.py
> +                ):
```suggestion
                if self.env.ref("g2p_registry_membership.group_membership_kind_head") in rec.role and rec.head_member:
```

2023-12-07 05:00 UTC, nhatnm0612 commented on spp_registry_wizard/wizard/create_member_wizard.py
> +                            head_member = members.individual.id
```suggestion
                for members in rec.group_id.group_membership_ids:
                    if self.env.ref("g2p_registry_membership.group_membership_kind_head") in members.kind:
                        head_member = members.individual.id
```

2024-01-23 00:41 UTC, closed without merging