added import match
openspp-project/openspp-registry pull request #237
Opened 2023-05-17 02:48 UTC by emjay0921

2023-06-05 03:44 UTC, reichie020212 submitted a review, later dismissed

2023-06-05 06:53 UTC, jeremi commented
@emjay0921 can you write test for it? 

Can you confirm it could work to import Individuals based on ID number?
Can you confirm it could work to import groups based on name?

2023-06-05 06:53 UTC, jeremi requested changes
Add tests

2023-06-05 13:25 UTC, emjay0921 commented
> @emjay0921 can you write test for it?
> 
> Can you confirm it could work to import Individuals based on ID number? Can you confirm it could work to import groups based on name?

I don't think it will be possible to add test on importing individual based on record ID as it is not fixed (As it was needed to be added in the CSV). It is possible to add it as an xml data first but wouldn't recommend it as it will be visible in Odoo.

2023-06-05 13:28 UTC, emjay0921 commented
> Add tests

Test added @jeremi .

2023-06-05 13:58 UTC, jeremi commented
@emjay0921 I ask ID number like the ID PASS number, or passport number...
Similarly it can be on phone number or email address.

2023-06-07 09:05 UTC, emjay0921 commented
> @emjay0921 I ask ID number like the ID PASS number, or passport number... Similarly it can be on phone number or email address.

Added a sub-field to set the right field to match if the field is one2many, many2one or many2many.

2023-06-22 02:41 UTC, jeremi commented
Can we have tests for this last changes?

2023-06-22 03:54 UTC, jeremi requested changes

2023-06-22 03:54 UTC, jeremi commented on spp_import_match/__manifest__.py
> +    "development_status": "Beta",
Make it Alpha

2023-07-07 05:31 UTC, nhatnm0612 commented on spp_import_match/models/import_match.py
> +    model_id = fields.Many2one(
I think there should be an unique constraint for model_id in spp import match, to narrow down the searching, and give us back better performance

2023-07-07 05:31 UTC, nhatnm0612 commented on spp_import_match/models/import_match.py
> +    model_id = fields.Many2one(related="match_id.model_id")
also should be an unique constraint for match_id and field_id in spp import match fields, that will be odd if we find 2 records pointing to only 1 field, right?

2023-07-07 05:31 UTC, nhatnm0612 commented on spp_import_match/models/import_match.py
> +        for record in available:
so if we have 2 sql constraints as I suggested, this function will be search with limit=1, save 1 for loop

2023-09-08 01:15 UTC, closed without merging