Renaming "g2p_entitlement_cash" to "spp_entitlement_cash"
openspp-project/openspp-registry pull request #385
Opened 2024-04-22 04:50 UTC by kneckinator

2024-04-25 00:59 UTC, gonzalesedwin1123 approved these changes

2024-05-07 03:43 UTC, emjay0921 approved these changes

2024-05-20 10:50 UTC, reichie020212 requested changes
@kneckinator pull branch 17.0 to fix GH Action and fix merge conflict.

2024-05-28 04:06 UTC, reichie020212 commented
> @kneckinator pull branch 17.0 and fix merge conflict.

2024-05-29 08:22 UTC, kneckinator commented
@reichie020212 rebased the branch on 17.0

2024-05-29 10:54 UTC, reichie020212 approved these changes

2024-05-31 09:26 UTC, merged