add target types on change requests
openspp-project/openspp-registry pull request #493
Opened 2024-07-25 07:35 UTC by emjay0921

## Why is this change needed?

To improve the handling of registrant domain

## How was the change implemented?

- New model was added to record the target types of each change requests types
- Added dynamic domain for registrant_id that will check on the change requests target

## New unit tests...

```
None
```

## Unit tests executed by the author...

```
spp_change_request_change_info/tests/test_create_cr.py::ChangeRequestChangeInfoTest
```

## How to test manually...
- Install or update the module `spp_change_request`.
- Install other CR modules e.g `spp_change_request_change_info`.
- To fully test install atleast 2 CR modules where the target is different.
- Navigate to Change Request.
- Create a Change Request.
- Select the Change Request Type.
- In the Registrant, see if the correct domain has been applied based on the Change Request Type Target.

## For Reference
- spp_change_request_change_info - Individual
- spp_change_request_add_children - Group
- spp_change_request_add_farmer - Group

## Links
- https://github.com/OpenSPP/openspp-modules/issues/294

2024-07-25 09:47 UTC, reichie020212 requested changes

2024-07-25 09:47 UTC, reichie020212 commented on spp_change_request/models/change_request.py
> +            rec.request_type_target = request_type_target
@emjay0921 , please move the `request_type_target = None` inside the for loop to reinitialize the variable every loop. Adding it outside then using it to a record's field may result to data error.

```suggestion
    def _compute_request_type_target(self):
        for rec in self:
            request_type_target = None
            if rec.request_type:
                request_type_targets = self.env["spp.change.request.targets"].search(
                    [("name", "=", rec.request_type)], limit=1
                )
                if request_type_targets:
                    request_type_target = request_type_targets.id

            rec.request_type_target = request_type_target
```

2024-07-29 06:43 UTC, reichie020212 approved these changes

2024-07-29 07:29 UTC, gonzalesedwin1123 approved these changes

2024-07-29 07:30 UTC, merged