fix issues on updating names and mobile no
openspp-project/openspp-registry pull request #547
Opened 2024-08-28 00:04 UTC by emjay0921

## **Why is this change needed?**
To fix the issues when creating names with special character and fix the updating of mobile number

## **How was the change implemented?**
Fixed the create and write functions for groups

## **New unit tests**
```
None
```

## **Unit tests executed by the author**
```
None
```

## **How to test manually**
- Install or Upgrade `spp_farmer_registry_base` and `spp_registrant_import`.

Issue 1:
- Create or Update a Group.
- In Farmer's Tab add a farmer with a special character name (e.g. O'Cronin).
- Save and Check if the name was not change to "O'cronin".

Issue 2:
- Create or Update a Group.
- In Farmer's Tab add a mobile number and Save.
- Try changing the mobile number again to see if it updates the mobile number.

## **Related links**
https://github.com/orgs/OpenSPP/projects/5/views/4?pane=issue&itemId=73820434

2024-08-28 03:16 UTC, reichie020212 commented
@emjay0921  Pull 17.0 branch and fix the error in test case TestRegistrant.test_06__inverse_name

2024-08-28 03:25 UTC, reichie020212 requested changes
Fix error in test case

2024-08-28 07:54 UTC, reichie020212 approved these changes

2024-09-03 03:35 UTC, gonzalesedwin1123 approved these changes

2024-10-10 03:28 UTC, merged