Added other SPP modules to OpenSPP category
openspp-project/openspp-registry pull request #563
Opened 2024-09-03 01:46 UTC by reichie020212

## **Why is this change needed?**

Some OpenSPP modules is not included in the OpenSPP Category

## **How was the change implemented?**

Added OpenSPP category in the manifest.py file

## **New unit tests**

No Unit Test

## **Unit tests executed by the author**

No Unit Test

## **How to test manually**

- Go to Apps Menu
- Click the `Update Apps List` button in the top part of the page and click `Update` button on the modal
- Reload the page.
- Remove the `Apps` filter in the search bar.
- in the Categories section, click the OpenSPP category.
- Check if all OpenSPP modules are included.

## **Related links**
https://github.com/OpenSPP/openspp-modules/issues/513

2024-09-03 03:50 UTC, gonzalesedwin1123 approved these changes

2024-09-03 04:51 UTC, kneckinator requested changes
If this PR should be released with the Batanes refresh (17.0.1.2.1), the target branch needs to be changed to `openspp-17.0.1.2.1` and it needs to be rebased on this branch.

Blocking merging until this has been decided.

2024-09-04 12:06 UTC, kneckinator commented
Changing ticket to draft, as it is not ready to merge according to QA findings. See: https://github.com/OpenSPP/openspp-modules/issues/513#issuecomment-2325408921

2024-09-04 12:36 UTC, reichie020212 commented
@kneckinator this PR is to address the comment https://github.com/OpenSPP/openspp-modules/issues/513#issuecomment-2325408921

2024-09-05 03:05 UTC, kneckinator commented
> If this PR should be released with the Batanes refresh (17.0.1.2.1), the target branch needs to be changed to `openspp-17.0.1.2.1` and it needs to be rebased on this branch.

Target `17.0` has been decided. Approving PR.

2024-09-05 03:05 UTC, kneckinator approved these changes

2024-09-06 03:57 UTC, merged