hide verify eligibility button on cycle view
openspp-project/openspp-registry pull request #564
Opened 2024-09-03 03:21 UTC by emjay0921

## **Why is this change needed?**
To hide `Verify Eligibility` button on cycle view

## **How was the change implemented?**
Added an attribute on cycle view to hide `Verify Eligibility` button if Program is Manual Eligibility

## **New unit tests**
```
None
```

## **Unit tests executed by the author**
```
None
```

## **How to test manually**
- Install or Upgrade `spp_manual_eligibility`.
- Navigate to a Program with Manual Eligibility as the Eligibility Manager.
- Create or Open a Cycle.
- Check if `Verify Eligibility` Button is hidden.

## **Related links**
https://github.com/OpenSPP/openspp-modules/issues/533

2024-09-03 05:20 UTC, reichie020212 requested changes

2024-09-03 05:20 UTC, reichie020212 commented on spp_manual_eligibility/models/cycle.py
> +                is_manual_eligibility = True
@emjay0921 you can just relate the field to the `is_manual_eligibility` field of g2p.program.

```suggestion
    is_manual_eligibility = fields.Boolean(related="program_id.is_manual_eligibility")
```

2024-09-05 04:34 UTC, reichie020212 approved these changes

2024-09-05 04:35 UTC, gonzalesedwin1123 approved these changes

2024-09-09 10:55 UTC, merged