Farmer registry default UI
openspp-project/openspp-registry pull request #598
Opened 2024-09-18 06:20 UTC by reichie020212

## **Why is this change needed?**

Need to create a new module to separate the farmer demo and farmer UI

## **How was the change implemented?**

Created a new module named spp_farmer_registry_default_ui and moved all of the ui codes of farmer demo to this new module

## **New unit tests**

None

## **Unit tests executed by the author**

None

## **How to test manually**

- Install spp_farmer_registry_default_ui module
- Check if it installed without error
- Check if the UI of Group Registry has changed.
- Check if there is a GIS View

- Install spp_farmer_registry_demo module
- Check if it installed without an error
- Check if all functionality of farmer registry demo still retains

## **Related links**

https://github.com/OpenSPP/openspp-modules/issues/567

2024-09-18 06:26 UTC, emjay0921 approved these changes

2024-09-18 06:27 UTC, gonzalesedwin1123 approved these changes

2024-09-18 06:39 UTC, kneckinator requested changes
There are a couple of issues:
- Branch contains merge commits from 17.0
  - It should be rebased on latest 17.0, which should remove the merge-commit
- Tests are not passing
  - Tests are passing in latest 17.0, rebasing should allow tests to pass

2024-09-18 07:04 UTC, kneckinator commented
> * Branch contains merge commits from 17.0
>   
>   * It should be rebased on latest 17.0, which should remove the merge-commit

Branch has been rebased – awaiting test results.

2024-10-01 03:44 UTC, kneckinator commented
> Branch has been rebased – awaiting test results.
Tests passed. Approving PR.

2024-10-01 03:44 UTC, kneckinator approved these changes

2024-10-10 03:28 UTC, merged