add gender data and educational level selections
openspp-project/openspp-registry pull request #617
Opened 2024-10-03 06:47 UTC by emjay0921

## **Why is this change needed?**
1. To not install `spp_base_demo` when `spp_farmer_registry_demo` is installed.
2. To fix the problem with the Highest Educational Level.

## **How was the change implemented?**
1. Removed `spp_base_demo` on `spp_farmer_registry_demo` depends, and add gender data xml.
2. Added the same selection values from `res_partner` to `spp_farmer`.

## **New unit tests**
```
None
```

## **Unit tests executed by the author**
```
None
```

## **How to test manually**
- Install `spp_farmer_registry_demo` on new instance or make sure `spp_base_demo` is not installed by uninstalling `spp_farmer_registry_demo` first.

Test 1
- Check if `spp_base_demo` is installed (should not be installed automatically).

Test 2
- Go to Configuration > Gender Types.
- Check if Male and Female are existing in the Gender Types.

Test 3
- Go to Group > Select or Open one.
- Check if Farmer Highest Educational Level selections is the same with Individual's Highest Educational Level.

## **Related links**
https://github.com/orgs/OpenSPP/projects/5/views/4?pane=issue&itemId=81324763

2024-10-03 09:15 UTC, reichie020212 requested changes
@emjay0921 as discussed earlier with @gonzalesedwin1123 , create a new module for the gender and locale provider. Thanks.

2024-10-04 02:46 UTC, emjay0921 commented
Sorry for the message of the latest commit, it was supposed to be "remove user data for program in spp_base_demo".

2024-10-07 07:42 UTC, gonzalesedwin1123 approved these changes

2024-10-08 02:23 UTC, reichie020212 approved these changes

2024-10-28 16:12 UTC, anjclarise commented
**_TEST 1:_** 
Upon checking spp_base_demo is installed (should not be installed automatically). spp_base_demo was only installed after adding spp_farmer_registry_demo. Regarding this, @reichie020212 @Markpenalosa  should this be the expected? In the **HOW TO TEST MANUALLY** is was specified that: 

>Install spp_farmer_registry_demo on new instance or make sure spp_base_demo is not installed by uninstalling spp_farmer_registry_demo first.

- spp_farmer_registry_demo not yet installed in a new instance
![image](https://github.com/user-attachments/assets/7e729615-d7e6-4937-b28c-2b8a72873585)

- spp_farmer_registry_demo already installed in the instance
![image](https://github.com/user-attachments/assets/079e1d59-5ba8-4d02-a109-74756e06fa58)

![image](https://github.com/user-attachments/assets/32651846-4142-4ae3-8103-58fdc36eb3ec)


**_TEST 2:_** 
-  Under Configuration >> Gender Types (Male and Female are NOT on the list) .
![image](https://github.com/user-attachments/assets/83fb3d2d-1a82-471b-98e6-7c8029011656)

**_TEST 3:_** 
- Individual highest education status: 
<img width="956" alt="image" src="https://github.com/user-attachments/assets/2d5110ce-0f25-46ad-8a57-6f75e321bc3b">

- Farmer highest education status:
<img width="953" alt="image" src="https://github.com/user-attachments/assets/50709a00-d345-4709-9180-05f6b465f822">

2024-11-11 05:53 UTC, merged