raise error when found multiple match
openspp-project/openspp-registry pull request #643
Opened 2024-10-24 03:54 UTC by emjay0921

## **Why is this change needed?**
To raise an error if import match found multiple matches.

## **How was the change implemented?**
Added a condition to check if matches found is greater that 1, then raise an error.

## **New unit tests**
```
None
```

## **Unit tests executed by the author**
```
None
```

## **How to test manually**
- Install or Upgrade `spp_import_match`
- Create an import match configuration for Contact (Registry > Configuration > Import Match)
- Check overwrite match, and Add `name` in Fields.
- Try importing with at least 2 existing duplicated name in Groups or Individuals.
- If error was raised this PR is done.

## **Related links**
https://github.com/OpenSPP/openspp-modules/issues/573

2024-10-24 05:15 UTC, reichie020212 requested changes

2024-10-24 05:15 UTC, reichie020212 commented on spp_import_match/models/import_match.py
> +                raise ValidationError(_(f"Multiple matches found for '{match[0].name}'!"))
@emjay0921 `_(f"")` is not a valid translation string. Use .format() or percentage format instead.

2024-10-25 01:13 UTC, reichie020212 approved these changes

2024-10-25 01:59 UTC, gonzalesedwin1123 approved these changes

2024-11-21 03:45 UTC, merged