Add Automatic Approval for OpenSPP Self-Reg Change Requests
openspp-project/openspp-registry pull request #653
Opened 2024-10-31 14:18 UTC by gonzalesedwin1123

## **Why is this change needed?**
A new function in the Change Request module is needed to support the direct approval and application of CRs submitted by the **OpenSPP Self-reg app**. The following will be provided by the new function:

- Accept CRs only from users belonging to the "**Change Request External API**" group.
- Validate the CR input data.
- Skip the validation of required attachments.
- Automatically approve the CR after the input data has been validated.

## **How was the change implemented?**

- A new function "**approve_cr**" was added to the **spp.change.request** model.
- This function can be called by external APIs (XMLRPC) authenticated with a user belonging to the "**Change Request External API**" group.

## **New unit tests**
None
## **Unit tests executed by the author**
None
## **How to test manually**

- Use the OpenSPP Self-reg app to create a new change request.
- Check the new change request in the OpenSPP change request UI.
- Its status must be automatically set to "Applied". 

## **Related links**
[Add Automatic Approval for OpenSPP Self-Reg Change Requests](https://github.com/OpenSPP/openspp-modules/issues/635)

2024-11-01 01:33 UTC, reichie020212 approved these changes

2024-11-05 08:29 UTC, emjay0921 approved these changes

2024-11-21 08:36 UTC, aldnav requested changes
Thanks for the swift support @gonzalesedwin1123 
Please check my comments.

2024-11-21 08:36 UTC, aldnav commented on spp_change_request/models/change_request.py
> +            ValidationError("User is not allowed to approve CRs directly.")
We need to raise this Validation Error. As the check is done but the CR is still approved for non-members of the security group.

![image](https://github.com/user-attachments/assets/8d820e3f-e06b-480d-a34d-7379f47945ac)

2024-11-21 08:36 UTC, aldnav commented on spp_change_request/models/mixins/source_mixin.py
> +            ValidationError("The request must be in draft, pending, or validated state for changes to be applied.")
Ditto raising Validation Error

2024-11-29 00:59 UTC, aldnav approved these changes
Thanks for a swift resolution @gonzalesedwin1123

2025-02-18 06:36 UTC, merged