able to update fields when calling scan passport api
openspp-project/openspp-registry pull request #98
Opened 2022-11-29 02:18 UTC by reichie020212

2022-11-29 03:35 UTC, jeremi requested changes
Use async ajax query

2022-11-29 06:29 UTC, reichie020212 commented
I have read the CLA Document and I hereby sign the CLA

2022-12-01 11:30 UTC, gonzalesedwin1123 approved these changes, later dismissed

2022-12-01 11:33 UTC, reichie020212 commented
recheck

2022-12-01 11:34 UTC, reichie020212 commented
recheck

2022-12-02 05:03 UTC, closed without merging